#VERSION=1.2
ARG ubuntuVersion="24.04"

FROM ubuntu:$ubuntuVersion

RUN apt update && apt install -y  \
    bash-completion  \
    btop  \
    cron  \
    curl  \
    git  \
    htop  \
    inetutils-ping  \
    jq  \
    net-tools  \
    rsync  \
    software-properties-common  \
    tzdata  \
    unzip \
    vim  \
    wget
ENV TZ="Europe/Berlin"

RUN LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
RUN LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/apache2

RUN apt update
RUN apt dist-upgrade -y

# https://getcomposer.org/doc/03-cli.md#bash-completions: RUN php composer.phar completion bash > /etc/bash_completion.d/composer // get via wget!
RUN wget https://raw.githubusercontent.com/wolxXx/toolz/main/composer_auto_complete.sh && mv composer_auto_complete.sh /etc/bash_completion.d/composer
RUN echo ". /etc/bash_completion" >> /root/.bashrc